# Generated by Django 3.2.15 on 2024-03-12 13:57

import crud.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Solicitud',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('fecha_i_t', models.DateField()),
                ('fecha_i_au', models.DateField()),
                ('N_transparencia', models.CharField(blank=True, default='', max_length=100)),
                ('dirigido', models.CharField(blank=True, default='Municipalidad de Valparaíso', max_length=100)),
                ('region', models.CharField(blank=True, default='Región de Valparaiso', max_length=100)),
                ('recepcion', models.CharField(blank=True, choices=[('CORREO ELECTRONICOS', 'CORREO ELECTRONICOS'), ('PAPEL', 'PAPEL')], default='', max_length=50)),
                ('email', models.CharField(blank=True, default='', max_length=150)),
                ('solicitud_text', models.TextField(blank=True, default='')),
                ('observaciones', models.TextField(blank=True, default='')),
                ('archivo_adjunto', models.ImageField(blank=True, default='', null=True, upload_to=crud.models.content_file_name_adjunto)),
                ('soporte', models.CharField(blank=True, default='', max_length=150)),
                ('formato', models.CharField(blank=True, default='', max_length=150)),
                ('solicitante_inicio_seccion', models.BooleanField(default=False)),
                ('forma_de_recepccion', models.CharField(blank=True, choices=[('CORREO ELECTRONICOS', 'CORREO ELECTRONICOS'), ('PAPEL', 'PAPEL')], default='', max_length=150)),
                ('otra_forma_De_entrega', models.CharField(blank=True, default='', max_length=150)),
                ('persona', models.CharField(blank=True, choices=[('NATURAL', 'NATURAL'), ('EMPRESA', 'EMPRESA')], default='', max_length=50)),
                ('nombre_o_razon_social', models.CharField(blank=True, default='', max_length=150)),
                ('primer_apellido', models.CharField(blank=True, default='', max_length=100)),
                ('segundo_apellido', models.CharField(blank=True, default='', max_length=100)),
                ('estado', models.CharField(blank=True, default='Sin responder', max_length=100)),
            ],
            options={
                'verbose_name': 'Solicitud',
                'verbose_name_plural': 'Solicitudes',
            },
        ),
        migrations.CreateModel(
            name='Respuesta_solicitud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField(blank=True, default='')),
                ('archivo_adjunto', models.ImageField(blank=True, default='', null=True, upload_to=crud.models.content_file_name_respuesta)),
                ('fecha_daj', models.DateField(blank=True)),
                ('id_solicitud', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crud.solicitud')),
            ],
            options={
                'verbose_name': 'Respuesta',
                'verbose_name_plural': 'Respuestas',
            },
        ),
    ]
