# Generated by Django 4.2.10 on 2024-03-14 12:59

import crud.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta_solicitud',
            name='archivo_adjunto_2',
            field=models.ImageField(blank=True, default='', null=True, upload_to=crud.models.content_file_name_respuesta),
        ),
        migrations.AddField(
            model_name='respuesta_solicitud',
            name='archivo_adjunto_3',
            field=models.ImageField(blank=True, default='', null=True, upload_to=crud.models.content_file_name_respuesta),
        ),
    ]
