# Generated by Django 4.2.10 on 2024-03-06 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_remove_respuesta_solicitud_solicitud_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='N_transparencia',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
