# Generated by Django 4.2.10 on 2024-04-16 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_solicitud_fecha_limite_solicitud_id_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='Departamento_admin',
            field=models.CharField(blank=True, choices=[('DEPARTAMENTO SIG', 'DEPARTAMENTO SIG'), ('ASESORIA URBANA', 'ASESORIA URBANA')], default='', max_length=150, null=True),
        ),
    ]
