# Generated by Django 4.2.10 on 2024-03-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_alter_solicitud_n_transparencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_i_au',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='fecha_i_t',
            field=models.DateField(),
        ),
    ]
