# Generated by Django 4.2.10 on 2024-03-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_alter_solicitud_fecha_i_au_alter_solicitud_fecha_i_t'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='estado',
            field=models.CharField(blank=True, default='Sin responder', max_length=100),
        ),
    ]
