# Generated by Django 3.2.15 on 2024-04-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_solicitud_departamento_admin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departamento',
            name='nombre_departamento',
            field=models.CharField(blank=True, choices=[('Departamento de Asesoría Urbana ', 'Departamento de Asesoría Urbana'), ('Departamento de Presupuesto Municipal y Control Financiero de Proyectos', 'Departamento de Presupuesto Municipal y Control Financiero de Proyectos'), ('Departamento de Planificación ', 'Departamento de Planificación'), ('Departamento de Estudios y Pre Inversión ', 'Departamento de Estudios y Pre Inversión'), ('Departamento de Sistema de Información Geográfica ', 'Departamento de Sistema de Información Geográfica'), ('ADMIN', 'ADMIN')], default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='Departamento_admin',
            field=models.CharField(blank=True, choices=[('Departamento de Asesoría Urbana ', 'Departamento de Asesoría Urbana'), ('Departamento de Presupuesto Municipal y Control Financiero de Proyectos', 'Departamento de Presupuesto Municipal y Control Financiero de Proyectos'), ('Departamento de Planificación ', 'Departamento de Planificación'), ('Departamento de Estudios y Pre Inversión ', 'Departamento de Estudios y Pre Inversión'), ('Departamento de Sistema de Información Geográfica ', 'Departamento de Sistema de Información Geográfica')], default='', max_length=150, null=True),
        ),
    ]
