# Generated by Django 4.2.10 on 2024-03-11 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_solicitud_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='respuesta_solicitud',
            name='fecha_daj',
            field=models.DateField(blank=True, default="2000-01-01"),
            preserve_default=False,
        ),
    ]
