# Generated by Django 3.2.15 on 2024-05-02 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0005_auto_20240416_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='forma_de_recepccion',
            field=models.CharField(blank=True, choices=[('CORREO ELECTRONICO', 'CORREO ELECTRONICO'), ('PAPEL', 'PAPEL')], default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='solicitud',
            name='recepcion',
            field=models.CharField(blank=True, choices=[('CORREO ELECTRONICO', 'CORREO ELECTRONICO'), ('PAPEL', 'PAPEL')], default='', max_length=50),
        ),
    ]
