# Generated by Django 3.2.15 on 2024-06-28 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0008_alter_respuesta_solicitud_id_solicitud'),
    ]

    operations = [
        migrations.AddField(
            model_name='solicitud',
            name='prorroga_realizada',
            field=models.BooleanField(default=False),
        ),
    ]
