# Generated by Django 4.2.10 on 2024-05-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pdf_link',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False, unique=True)),
                ('id_excel', models.IntegerField()),
                ('fecha_I', models.DateField()),
                ('fecha_E', models.DateField()),
                ('nombre', models.CharField(blank=True, default='', max_length=100)),
            ],
            options={
                'verbose_name': 'Pdf_link',
                'verbose_name_plural': 'Pdf_links',
            },
        ),
    ]
